// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTyPE7baA9tNc5c11nxlk8cO_LR5k2HU',
    appId: '1:302191973529:web:b8aefc9352f0b517c7d408',
    messagingSenderId: '302191973529',
    projectId: 'auto-ride-supperapp',
    authDomain: 'auto-ride-supperapp.firebaseapp.com',
    storageBucket: 'auto-ride-supperapp.firebasestorage.app',
    measurementId: 'G-R8VBHQEZMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZwBODjZrztUHv-3aocywA8kpdULu5E8',
    appId: '1:302191973529:android:e8a85ef3623fe0cac7d408',
    messagingSenderId: '302191973529',
    projectId: 'auto-ride-supperapp',
    storageBucket: 'auto-ride-supperapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm7mk3Nqxp1dYE8E-Nnsv-EIpusTOy7BE',
    appId: '1:302191973529:ios:35e385a44a6b42cbc7d408',
    messagingSenderId: '302191973529',
    projectId: 'auto-ride-supperapp',
    storageBucket: 'auto-ride-supperapp.firebasestorage.app',
    iosBundleId: 'com.example.autorideSuperapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm7mk3Nqxp1dYE8E-Nnsv-EIpusTOy7BE',
    appId: '1:302191973529:ios:35e385a44a6b42cbc7d408',
    messagingSenderId: '302191973529',
    projectId: 'auto-ride-supperapp',
    storageBucket: 'auto-ride-supperapp.firebasestorage.app',
    iosBundleId: 'com.example.autorideSuperapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiTyPE7baA9tNc5c11nxlk8cO_LR5k2HU',
    appId: '1:302191973529:web:bda81f62ce6ea1dec7d408',
    messagingSenderId: '302191973529',
    projectId: 'auto-ride-supperapp',
    authDomain: 'auto-ride-supperapp.firebaseapp.com',
    storageBucket: 'auto-ride-supperapp.firebasestorage.app',
    measurementId: 'G-WR2K8B2GR0',
  );

}